-- =========================================================
-- Smart Desk Booking System
-- V1 - Initial Database Schema
-- =========================================================


-- =========================================================
-- 1. PostgreSQL extension required for exclusion constraint
-- =========================================================

CREATE EXTENSION IF NOT EXISTS btree_gist;


-- =========================================================
-- 2. Teams
-- =========================================================

CREATE TABLE teams (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                       name VARCHAR(100) NOT NULL,

                       created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                       updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

                       CONSTRAINT uk_team_name
                           UNIQUE (name)
);


-- =========================================================
-- 3. Users
-- =========================================================

CREATE TABLE users (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                       employee_code VARCHAR(50) NOT NULL,
                       name VARCHAR(150) NOT NULL,
                       email VARCHAR(255) NOT NULL,
                       password_hash VARCHAR(255) NOT NULL,

                       role VARCHAR(30) NOT NULL DEFAULT 'EMPLOYEE',

                       team_id BIGINT NOT NULL,

                       active BOOLEAN NOT NULL DEFAULT TRUE,

                       created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                       updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

                       CONSTRAINT uk_user_employee_code
                           UNIQUE (employee_code),

                       CONSTRAINT uk_user_email
                           UNIQUE (email),

                       CONSTRAINT fk_user_team
                           FOREIGN KEY (team_id)
                               REFERENCES teams(id)
);


CREATE INDEX idx_users_team_id
    ON users(team_id);


-- =========================================================
-- 4. Floors
-- =========================================================

CREATE TABLE floors (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                        building VARCHAR(100) NOT NULL,
                        floor_number INTEGER NOT NULL,
                        name VARCHAR(100) NOT NULL,
                        timezone VARCHAR(50) NOT NULL,

                        created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                        updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

                        CONSTRAINT uk_floor_building_number
                            UNIQUE (building, floor_number)
);


-- =========================================================
-- 5. Floor-Team Quotas
-- =========================================================

CREATE TABLE floor_team_quotas (
                                   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                                   floor_id BIGINT NOT NULL,
                                   team_id BIGINT NOT NULL,

                                   max_concurrent_bookings INTEGER NOT NULL,

                                   CONSTRAINT fk_quota_floor
                                       FOREIGN KEY (floor_id)
                                           REFERENCES floors(id),

                                   CONSTRAINT fk_quota_team
                                       FOREIGN KEY (team_id)
                                           REFERENCES teams(id),

                                   CONSTRAINT uk_quota_floor_team
                                       UNIQUE (floor_id, team_id),

                                   CONSTRAINT ck_quota_positive
                                       CHECK (max_concurrent_bookings > 0)
);


-- =========================================================
-- 6. Desks
-- =========================================================

CREATE TABLE desks (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                       floor_id BIGINT NOT NULL,

                       desk_number VARCHAR(50) NOT NULL,

                       x_coordinate INTEGER NOT NULL,
                       y_coordinate INTEGER NOT NULL,

                       desk_type VARCHAR(20) NOT NULL,
                       status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',

                       assigned_user_id BIGINT,

                       created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                       updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

                       CONSTRAINT fk_desk_floor
                           FOREIGN KEY (floor_id)
                               REFERENCES floors(id),

                       CONSTRAINT fk_desk_assigned_user
                           FOREIGN KEY (assigned_user_id)
                               REFERENCES users(id),

                       CONSTRAINT uk_desk_number_per_floor
                           UNIQUE (floor_id, desk_number),

                       CONSTRAINT ck_desk_type
                           CHECK (desk_type IN ('FIXED', 'HOT')),

                       CONSTRAINT ck_desk_status
                           CHECK (status IN ('ACTIVE', 'INACTIVE')),

                       CONSTRAINT ck_desk_assignment
                           CHECK (
                               (desk_type = 'FIXED' AND assigned_user_id IS NOT NULL)
                                   OR
                               (desk_type = 'HOT' AND assigned_user_id IS NULL)
                               )
);


CREATE INDEX idx_desks_floor_status
    ON desks(floor_id, status);


-- =========================================================
-- 7. Bookings
-- =========================================================

CREATE TABLE bookings (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                          user_id BIGINT NOT NULL,
                          desk_id BIGINT NOT NULL,

                          start_time TIMESTAMPTZ NOT NULL,
                          end_time TIMESTAMPTZ NOT NULL,

                          status VARCHAR(20) NOT NULL DEFAULT 'CONFIRMED',

                          created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                          updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

                          CONSTRAINT fk_booking_user
                              FOREIGN KEY (user_id)
                                  REFERENCES users(id),

                          CONSTRAINT fk_booking_desk
                              FOREIGN KEY (desk_id)
                                  REFERENCES desks(id),

                          CONSTRAINT ck_booking_time
                              CHECK (start_time < end_time),

                          CONSTRAINT ck_booking_status
                              CHECK (
                                  status IN (
                                             'CONFIRMED',
                                             'CANCELLED',
                                             'NO_SHOW',
                                             'COMPLETED'
                                      )
                                  )
);


-- =========================================================
-- 8. Booking lookup index
-- =========================================================

CREATE INDEX idx_bookings_desk_time
    ON bookings(desk_id, start_time, end_time);


-- =========================================================
-- 9. Prevent overlapping CONFIRMED bookings
--    for the same desk
-- =========================================================

ALTER TABLE bookings
    ADD CONSTRAINT ex_confirmed_booking_no_overlap
    EXCLUDE USING GIST (
    desk_id WITH =,
    tstzrange(start_time, end_time, '[)') WITH &&
)
WHERE (status = 'CONFIRMED');